const test=require('node:test');const assert=require('node:assert/strict');
const store=require('../api/supplements-store.cjs');
function memory(){let value=null;return{get:async()=>value,set:async(_k,next)=>{value=structuredClone(next);return true}}}

test('supplement delete and undo restore cached AI description',async()=>{store.resetMutationQueuesForTests();const cache=memory(),options={cache,now:Date.parse('2026-09-26T18:00:00Z')};const added=await store.addSupplement('Рустам','Магний',options);const described=await store.saveSupplementDescription('Рустам',added.item.id,'Краткое научное описание.',{...options,now:Date.parse('2026-09-26T18:01:00Z')});assert.equal(described.item.description,'Краткое научное описание.');const removed=await store.removeSupplement('Рустам',added.item.id,{...options,now:Date.parse('2026-09-26T18:02:00Z')});assert.equal(removed.state.items.length,0);const restored=await store.restoreSupplement('Рустам',removed.removed,{...options,now:Date.parse('2026-09-26T18:03:00Z')});assert.equal(restored.item.description,'Краткое научное описание.');assert.equal(restored.state.items.length,1)});

test('supplements are separated by actor',async()=>{store.resetMutationQueuesForTests();const rustam=memory(),diana=memory();await store.addSupplement('Рустам','Омега-3',{cache:rustam});await store.addSupplement('Диана','Витамин D',{cache:diana});assert.equal((await store.readSupplements('Рустам',{cache:rustam})).items[0].name,'Омега-3');assert.equal((await store.readSupplements('Диана',{cache:diana})).items[0].name,'Витамин D')});

test('old supplement records get safe defaults',()=>{const item=store.normalizeItem({id:'x',name:'Магний',createdAt:'2026-09-26T00:00:00Z',updatedAt:'2026-09-26T00:00:00Z'});assert.equal(item.status,'active');assert.deepEqual(item.schedule,{dosage:'',time:'',food:'any'});assert.deepEqual(item.course,{startDate:'',durationDays:0});assert.deepEqual(item.intakes,[])});

test('supplement settings, status history and intake persist',async()=>{store.resetMutationQueuesForTests();const cache=memory(),base=Date.parse('2026-09-26T07:00:00Z');const added=await store.addSupplement('Рустам','Креатин',{cache,now:base});const id=added.item.id;const updated=await store.updateSupplement('Рустам',id,{goal:'Спорт',ingredients:'Креатин моногидрат',schedule:{dosage:'5 г',time:'09:00',food:'with'},course:{startDate:'2026-09-26',durationDays:30},status:'paused',expirationDate:'2027-01-01'},{cache,now:base+1000});assert.equal(updated.item.goal,'Спорт');assert.equal(updated.item.schedule.time,'09:00');assert.equal(updated.item.status,'paused');assert.equal(updated.item.statusHistory.length,1);await store.updateSupplement('Рустам',id,{status:'active'},{cache,now:base+2000});const first=await store.markSupplementTaken('Рустам',id,{cache,now:base+3000});const second=await store.markSupplementTaken('Рустам',id,{cache,now:base+4000});assert.equal(first.duplicate,false);assert.equal(second.duplicate,true);assert.equal(second.item.intakes.length,1)});

test('daily recommendation is kept once per date',async()=>{store.resetMutationQueuesForTests();const cache=memory(),base={cache,now:Date.parse('2026-09-26T10:00:00Z')};const first=await store.saveDailyRecommendation('Рустам',{date:'2026-09-26',text:'Первый совет',age:34,sex:'male'},base);assert.equal(first.saved,true);const second=await store.saveDailyRecommendation('Рустам',{date:'2026-09-26',text:'Другой совет',age:34,sex:'male'},{...base,now:Date.parse('2026-09-26T12:00:00Z')});assert.equal(second.saved,false);assert.equal(second.recommendation.text,'Первый совет')});