const crypto=require('node:crypto');const {getControlPlaneCache}=require('./stateful-cache.cjs');
function cacheOf(o={}){return o.cache||getControlPlaneCache(o.cacheOptions||{})}
function norm(v){return String(v||'').toLowerCase().replace(/\s+/g,' ').trim().slice(0,500)}
function fingerprintAlert(a){return crypto.createHash('sha256').update(JSON.stringify({code:norm(a.code),section:norm(a.section),message:norm(a.message)})).digest('hex')}
async function defaultSend(text,o={}){const {resolveTelegramBotToken}=require('./products-bought.cjs');const {getKnownForumChatId,handleTelegramTopicRequest}=require('./topic-maintenance.cjs');const token=resolveTelegramBotToken(o.env||process.env);const chatId=await getKnownForumChatId();if(!chatId)throw new Error('Alert chat id unavailable');const url=`https://api.telegram.org/bot${token}/sendMessage`;const init={method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:chatId,text,disable_notification:true})};const response=await handleTelegramTopicRequest(url,init,{fetchImpl:o.fetchImpl||globalThis.fetch});if(!response?.ok)throw new Error(`Alert Telegram HTTP ${response?.status||0}`)}
async function emitOperationalAlert(alert,o={}){const fp=fingerprintAlert(alert);const c=cacheOf(o);const key=`alert:${fp}`;const now=o.now instanceof Date?o.now:new Date(o.now||Date.now());const previous=await c.get(key);const minutes=Math.max(1,Number(o.dedupeMinutes||180));if(previous&&now.getTime()-new Date(previous.sentAt).getTime()<minutes*60000)return{sent:false,suppressed:true,fingerprint:fp};const text=`⚠️ RUDI: ${String(alert.section||'система')} — ${String(alert.message||alert.code||'ошибка').slice(0,600)}`;const send=o.send||((t)=>defaultSend(t,o));await send(text);const row={fingerprint:fp,code:String(alert.code||''),section:String(alert.section||''),message:String(alert.message||''),sentAt:now.toISOString(),acknowledgedAt:null};await c.set(key,row,{tags:['rudi-alerts']});await c.set('alerts:latest',row,{tags:['rudi-alerts']});return{sent:true,suppressed:false,fingerprint:fp}}
async function acknowledgeAlert(fp,o={}){const c=cacheOf(o);const key=`alert:${String(fp)}`;const row=await c.get(key);if(!row)return null;row.acknowledgedAt=new Date(o.now||Date.now()).toISOString();await c.set(key,row,{tags:['rudi-alerts']});return row}
async function getAlertState(o={}){return cacheOf(o).get('alerts:latest')}
module.exports={fingerprintAlert,emitOperationalAlert,acknowledgeAlert,getAlertState};
