const http=require('node:http');
const crypto=require('node:crypto');
const {WebSocketServer,WebSocket}=require('ws');
const {verifyMessengerRealtimeToken}=require('./realtime-auth.cjs');
const EVENTS=new Set(['message','reaction','edit','delete','read','delivered','typing','presence']),clients=new Set(),traces=new Map();
const json=(res,s,v)=>{res.statusCode=s;res.setHeader('content-type','application/json');res.setHeader('cache-control','no-store');res.end(JSON.stringify(v))};
const traceId=v=>/^[A-Za-z0-9:_-]{8,120}$/.test(String(v||''))?String(v):'rt-'+crypto.randomUUID();
const server=http.createServer((req,res)=>req.method==='GET'?json(res,200,{ok:true,realtime:'vercel-websocket',clients:clients.size}):json(res,405,{ok:false}));
const wss=new WebSocketServer({noServer:true,maxPayload:512*1024});
server.on('upgrade',(req,socket,head)=>{try{const url=new URL(req.url||'/','https://'+String(req.headers.host||'localhost')),auth=verifyMessengerRealtimeToken(url.searchParams.get('token'),{env:process.env});wss.handleUpgrade(req,socket,head,ws=>{ws.rudiActor=auth.actor;wss.emit('connection',ws,req)})}catch(_){try{socket.write('HTTP/1.1 401 Unauthorized\r\nConnection: close\r\n\r\n')}catch(_){};try{socket.destroy()}catch(_){}}});
wss.on('connection',ws=>{clients.add(ws);ws.send(JSON.stringify({type:'ready',actor:ws.rudiActor,at:Date.now()}));ws.on('message',raw=>{const text=String(raw||'');if(text==='ping'){try{ws.send(JSON.stringify({type:'pong',at:Date.now()}))}catch(_){};return}let d;try{d=JSON.parse(text)}catch(_){return}
if(d?.type==='ack'){const id=traceId(d.traceId),t=traces.get(id);if(t)console.info('RUDI_REALTIME_RECIPIENT_TIMING',JSON.stringify({traceId:id,event:t.event,from:t.actor,to:ws.rudiActor,dbToPublishMs:t.dbCommittedAt?t.publishedAt-t.dbCommittedAt:null,publishToRecipientMs:Date.now()-t.publishedAt,requestToRecipientMs:t.apiReceivedAt?Date.now()-t.apiReceivedAt:null}));return}
if(d?.type!=='publish'||!EVENTS.has(String(d.event||'')))return;const event=String(d.event),payload=d.payload&&typeof d.payload==='object'&&!Array.isArray(d.payload)?{...d.payload}:{};payload.actor=ws.rudiActor;const id=traceId(d.traceId),publishedAt=Date.now(),apiReceivedAt=Number(d.apiReceivedAt||0)||0,dbCommittedAt=Number(d.dbCommittedAt||0)||0;traces.set(id,{event,actor:ws.rudiActor,publishedAt,apiReceivedAt,dbCommittedAt});for(const[k,t]of traces)if(publishedAt-t.publishedAt>60000)traces.delete(k);const frame=JSON.stringify({type:'sync',event,payload,traceId:id,publishedAt});let recipients=0;for(const c of clients){if(c===ws||c.readyState!==WebSocket.OPEN)continue;try{c.send(frame);recipients++}catch(_){}}console.info('RUDI_REALTIME_PUBLISH_TIMING',JSON.stringify({traceId:id,event,actor:ws.rudiActor,recipients,dbToPublishMs:dbCommittedAt?publishedAt-dbCommittedAt:null,requestToPublishMs:apiReceivedAt?publishedAt-apiReceivedAt:null}))});ws.on('close',()=>clients.delete(ws));ws.on('error',()=>clients.delete(ws))});
module.exports=server;
