const crypto=require('node:crypto');
const {createStrictRuntimeCache}=require('./strict-runtime-cache.cjs');
const NAMESPACE='rudi-supplements-v1',TTL_SECONDS=315360000,MAX_ITEMS=80,ACTORS=new Set(['Рустам','Диана']);
const tails=new Map();
function cleanActor(v){const a=String(v||'').trim();if(!ACTORS.has(a))throw new Error('supplements-actor-invalid');return a}
function cleanText(v,m=700){return String(v||'').replace(/\s+/g,' ').trim().slice(0,m)}
function keyFor(a){return 'supplements:'+cleanActor(a)}
function cacheOf(o={}){return o.supplementsCache||o.cache||createStrictRuntimeCache({namespace:NAMESPACE,...(o.cacheOptions||{})})}
function normalizeItem(input){if(!input||typeof input!=='object')return null;const id=cleanText(input.id,96),name=cleanText(input.name,120);if(!id||!name)return null;const created=new Date(input.createdAt||0),updated=new Date(input.updatedAt||input.createdAt||0);if(Number.isNaN(created.getTime())||Number.isNaN(updated.getTime()))return null;const described=input.describedAt?new Date(input.describedAt):null;return{id,name,description:cleanText(input.description,700),createdAt:created.toISOString(),updatedAt:updated.toISOString(),describedAt:described&&!Number.isNaN(described.getTime())?described.toISOString():''}}
function normalizeState(value,actor){const who=cleanActor(actor),source=value&&typeof value==='object'&&!Array.isArray(value)?value:{};return{initialized:Boolean(source.initialized),version:Math.max(0,Number(source.version||0)),actor:who,items:(Array.isArray(source.items)?source.items:[]).map(normalizeItem).filter(Boolean).slice(0,MAX_ITEMS),updatedAt:cleanText(source.updatedAt,40)}}
function enqueue(actor,task){const key=cleanActor(actor),tail=tails.get(key)||Promise.resolve(),run=tail.then(task,task);tails.set(key,run.catch(()=>{}));return run}
async function readSupplements(actor,o={}){const who=cleanActor(actor);return normalizeState(await cacheOf(o).get(keyFor(who)),who)}
async function writeSupplements(actor,state,o={}){const who=cleanActor(actor),now=new Date(o.now||Date.now()).toISOString(),next=normalizeState({...state,initialized:true,actor:who,updatedAt:now},who);await cacheOf(o).set(keyFor(who),next,{ttl:TTL_SECONDS,tags:['rudi-supplements'],name:keyFor(who)});return next}
async function addSupplement(actor,name,o={}){const who=cleanActor(actor),safe=cleanText(name,120);if(!safe)throw new Error('supplement-name-required');return enqueue(who,async()=>{const state=await readSupplements(who,o);if(state.items.some(i=>i.name.localeCompare(safe,'ru',{sensitivity:'accent'})===0))throw new Error('supplement-duplicate');if(state.items.length>=MAX_ITEMS)throw new Error('supplement-limit');const now=new Date(o.now||Date.now()).toISOString(),item={id:'supp-'+crypto.randomUUID(),name:safe,description:'',createdAt:now,updatedAt:now,describedAt:''},saved=await writeSupplements(who,{...state,version:state.version+1,items:[item,...state.items]},o);return{state:saved,item:saved.items.find(r=>r.id===item.id)||item}})}
async function removeSupplement(actor,id,o={}){const who=cleanActor(actor),safe=cleanText(id,96);if(!safe)throw new Error('supplement-id-required');return enqueue(who,async()=>{const state=await readSupplements(who,o),index=state.items.findIndex(i=>i.id===safe);if(index<0)throw new Error('supplement-not-found');const removed=state.items[index],saved=await writeSupplements(who,{...state,version:state.version+1,items:state.items.filter(i=>i.id!==safe)},o);return{state:saved,removed}})}
async function restoreSupplement(actor,input,o={}){const who=cleanActor(actor),item=normalizeItem(input);if(!item)throw new Error('supplement-restore-invalid');return enqueue(who,async()=>{const state=await readSupplements(who,o),existing=state.items.find(i=>i.id===item.id);if(existing)return{state,item:existing,restored:false};const saved=await writeSupplements(who,{...state,version:state.version+1,items:[item,...state.items].slice(0,MAX_ITEMS)},o);return{state:saved,item:saved.items.find(i=>i.id===item.id)||item,restored:true}})}
async function saveSupplementDescription(actor,id,description,o={}){const who=cleanActor(actor),safeId=cleanText(id,96),safeDescription=cleanText(description,700);if(!safeId)throw new Error('supplement-id-required');if(!safeDescription)throw new Error('supplement-description-empty');return enqueue(who,async()=>{const state=await readSupplements(who,o),index=state.items.findIndex(i=>i.id===safeId);if(index<0)throw new Error('supplement-not-found');if(state.items[index].description)return{state,item:state.items[index],saved:false};const now=new Date(o.now||Date.now()).toISOString(),items=[...state.items];items[index]={...items[index],description:safeDescription,describedAt:now,updatedAt:now};const saved=await writeSupplements(who,{...state,version:state.version+1,items},o);return{state:saved,item:saved.items[index],saved:true}})}
function resetMutationQueuesForTests(){tails.clear()}
module.exports={NAMESPACE,TTL_SECONDS,MAX_ITEMS,normalizeItem,normalizeState,readSupplements,writeSupplements,addSupplement,removeSupplement,restoreSupplement,saveSupplementDescription,resetMutationQueuesForTests};